// <auto-generated />
namespace Softtek.Academy2018.Demo.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddingProjects : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingProjects));
        
        string IMigrationMetadata.Id
        {
            get { return "201802170234595_AddingProjects"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
